version: '3'

services:

  mysql-development:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp2
    ports:
      - "3306:3306"

  admin:
    image: adminer
    ports:
      - "8081:8081"